### PR TITLE
Implements SequenceType, can be used for for-in loop

### PR DESCRIPTION
**Pull request by ikesyo**

### CODE REVIEW

**Comment by robrix** [comment]
Interesting; I’m not sure I understand the value of this relative to `[ box.value ]`, however. Could you describe the intended use case?

**Comment by ikesyo** [comment]
Oh, I didn't think about `[ box.value ]`. This is basically from my interest, `Box` seems a collection which have just one element.

And sometimes I want to use the unboxed value multiple times, but store it to a temporary constant is a bit tiresome. Using for-in loop is preferable for me for that use case.

```swift
let value = box.value
if predicate(value) {
    someMethodWithValue(value)
}

// or

for value in box {
    if predicate(value) {
        someMethodWithValue(value)
    }
}

**Comment by robrix** [comment]
Ah, ok. I think this is an interesting use case, but it’s not something I want to support going forward. That said, thank you for the PR!

**Comment by ikesyo** [comment]
Thanks for your consideration. :sweat_smile:

**Pull request closed without merging**
