### PR TITLE
Added podspec

### PR DESCRIPTION
**Pull request by laptobbe**
Added a podspec that passes lint. I think it's better if you push it to the trunk. If you think it is a god idea to be on cocoapods. :)

### CODE REVIEW

**Comment by robrix** [comment]
Hi @laptobbe, thanks for the pull request!

Podspecs don‘t need to be added to the repository, and since I don’t use CocoaPods I won’t be able to maintain it. I’d suggest that instead you push it to the specs repo [per their documentation](http://guides.cocoapods.org/making/specs-and-specs-repo.html).

I’m going to close this out now, but thank you again for the effort!

**Comment by gfontenot** [comment]
If there's no objection from y'all I'm happy to manage this. We need `Box` to be in CocoaPods in order to have it as a dependency for [Argo](https://github.com/thoughtbot/Argo), so I have an interest in making sure it's available.

**Comment by robrix** [comment]
:ok_hand:

**Comment by gfontenot** [comment]
Done. All tagged versions of Box are now available through CocoaPods. Thanks for putting the podspec together, @laptobbe!

**Pull request closed without merging**
